### ISSUE TITLE
Allow to specify application version

### ISSUE THREAD

**Issue by lapkritinis** [snowplow-devops/terraform-aws-transformer-kinesis-ec2#4]
Hello, now docker image version is hardcoded and set to 3.0.0. It was released 8 months ago. Currently app is at 5.1.0 or somewhere around. Therefore I would like to ask to add app_version parameter to specify which version to run.

**Comment by jbeemster** [comment]
Hey @lapkritinis we can certainly make this more flexible.  However allowing any version is prone to breaking as the config is not guaranteed to be compatible between major versions.  Will add to the list to give all of our OS modules a refresh on versions!

**Comment by jbeemster** [comment]
Hey @lapkritinis I have now released v0.2.0 which is now running v5.2.0 of the application with a bunch of fixes related to memory allocation.

**Comment by jbeemster** [comment]
Closing as `app_version` is now exposed as an input variable which should solve this problem!
